name: Check Arch News
on:
  # schedule:
  #   # At minute 30 past every 6th hour.
  #   - cron: "30 */6 * * *"
  workflow_dispatch:

jobs:
  Run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v3
      - uses: swatinem/rust-cache@v2

      - name: Run program
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: cargo run --release
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto update last title"
          file_pattern: "last_title.txt"
